using matrix_project.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace matrix_project.Utils
{

    /// <summary>
    /// Utility class for matrix operations.
    /// </summary>
    public static class MatrixUtils
    {
        /// <summary>
        /// Generates a random matrix with specified dimensions, filled with values generated by the provided function.
        /// </summary>
        /// <typeparam name="T">The type of elements in the matrix, must be a struct implementing IConvertible.</typeparam>
        /// <param name="rows">The number of rows in the matrix.</param>
        /// <param name="cols">The number of columns in the matrix.</param>
        /// <param name="randomValueGenerator">A function that generates random values of type T.</param>
        /// <returns>A 2D array (matrix) of type T with the specified dimensions, filled with values from the random value generator.</returns>
        /// <exception cref="ArgumentException">Thrown when rows or columns are less than or equal to zero.</exception>
        /// <exception cref="ArgumentNullException">Thrown when the random value generator function is null.</exception>
        public static T[,] GenerateRandomMatrix<T>(
            int rows,
            int cols,
            Func<T> randomValueGenerator)
        {
            if (rows <= 0 || cols <= 0)
                throw new ArgumentException("Matrix dimensions must be positive.");
            if (randomValueGenerator == null)
                throw new ArgumentNullException(nameof(randomValueGenerator));

            var matrix = new T[rows, cols];
            for (int r = 0; r < rows; r++)
                for (int c = 0; c < cols; c++)
                    matrix[r, c] = randomValueGenerator();

            return matrix;
        }

        /// <summary>
        /// Prints a matrix to the console with optional size limits.
        /// </summary>
        /// <typeparam name="T">The type of elements in the matrix.</typeparam>
        /// <param name="matrix">The matrix to print.</param>
        /// <param name="maxRows">Maximum number of rows to print.</param>
        /// <param name="maxCols">Maximum number of columns to print.</param>
        /// <exception cref="ArgumentNullException">Thrown if the matrix is null.</exception>
        public static void PrintMatrix<T>(IMatrix<T> matrix, int maxRows = 10, int maxCols = 10)
        {
            if (matrix == null)
                throw new ArgumentNullException(nameof(matrix));

            var rows = Math.Min(matrix.RowCount, maxRows);
            var cols = Math.Min(matrix.ColCount, maxCols);

            for (var r = 0; r < rows; r++)
            {
                for (var c = 0; c < cols; c++)
                {
                    var value = matrix[r, c];
                    Console.Write(value is IFormattable f ? $"{f.ToString("F2", null),-8}" : $"{value,-8}");
                }
                Console.WriteLine(cols < matrix.ColCount ? "..." : "");
            }

            if (rows < matrix.RowCount)
                Console.WriteLine("...");
        }

        /// <summary>
        /// Проверяет равенство двух матриц с точностью epsilon.
        /// </summary>
        /// <param name="a">Первая матрица.</param>
        /// <param name="b">Вторая матрица.</param>
        /// <param name="epsilon">Допустимая погрешность сравнения.</param>
        /// <param name="mismatchRow">Номер строки первого несоответствия (если найдено).</param>
        /// <param name="mismatchCol">Номер столбца первого несоответствия (если найдено).</param>
        /// <returns>True, если матрицы равны с учётом epsilon, иначе false.</returns>
        public static bool AreMatricesEqual(IMatrix<double> a, IMatrix<double> b, double epsilon, out int mismatchRow, out int mismatchCol)
        {
            mismatchRow = -1;
            mismatchCol = -1;

            if (a.RowCount != b.RowCount || a.ColCount != b.ColCount)
                return false;

            for (int i = 0; i < a.RowCount; i++)
            {
                for (int j = 0; j < a.ColCount; j++)
                {
                    if (Math.Abs(a[i, j] - b[i, j]) > epsilon)
                    {
                        mismatchRow = i;
                        mismatchCol = j;
                        return false;
                    }
                }
            }
            return true;
        }

        // Перегрузка с epsilon по умолчанию, без out параметров
        public static bool AreMatricesEqual(IMatrix<double> a, IMatrix<double> b, double epsilon)
        {
            return AreMatricesEqual(a, b, epsilon, out _, out _);
        }
    }
}
